version: '3.3'

services:
  server:
    container_name: minecraft_server
    hostname: minecraft.ws
    build:
      context: './'
    ports:
      - "25565:25565"
      - "8123:8123"
    volumes:
      - '.:/home/app'
    network_mode: bridge
